# Generated by Django 5.1.4 on 2024-12-23 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='course',
        ),
        migrations.AddField(
            model_name='professor',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='professors', to='main_app.course'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='main_app.schedule'),
        ),
    ]
