# Generated by Django 5.1.4 on 2024-12-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='category',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('BORROWED', 'Borrowed')], default='OTHER', max_length=100),
        ),
    ]
