# Generated by Django 5.1.4 on 2024-12-25 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_delete_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['date', 'time']},
        ),
        migrations.AlterField(
            model_name='schedule',
            name='type',
            field=models.CharField(choices=[('ON_CAMPUS', 'On Campus'), ('ONLINE', 'Online'), ('LAB', 'Laboratory'), ('TUTORIAL', 'Tutorial')], default='ON_CAMPUS', max_length=50),
        ),
    ]
