# Generated by Django 5.1.4 on 2025-01-01 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_library_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='student_id',
        ),
        migrations.AlterField(
            model_name='library',
            name='category',
            field=models.CharField(choices=[('FICTION', 'Fiction'), ('NON_FICTION', 'Non-Fiction'), ('SCIENCE', 'Science'), ('HISTORY', 'History'), ('MATH', 'Mathematics'), ('BIOLOGY', 'Biology'), ('PHYSICS', 'Physics'), ('CHEMISTRY', 'Chemistry'), ('ENGINEERING', 'Engineering'), ('MEDICINE', 'Medicine'), ('BUSINESS', 'Business'), ('LITERATURE', 'Literature'), ('PHILOSOPHY', 'Philosophy'), ('PSYCHOLOGY', 'Psychology'), ('SOCIOLOGY', 'Sociology'), ('POLITICAL_SCIENCE', 'Political Science'), ('ECONOMICS', 'Economics'), ('ART', 'Art'), ('MUSIC', 'Music'), ('SPORTS', 'Sports'), ('NOVEL', 'Novel'), ('SCIENCE_FICTION', 'Science Fiction'), ('THRILLER', 'Thriller'), ('PERSONAL_DEVELOPMENT', 'Personal Development'), ('COMPUTER_TECHNOLOGY', 'Computer Technology'), ('COMPUTER_SCIENCE', 'Computer Science'), ('OTHER', 'Other')], default='OTHER', max_length=100),
        ),
    ]
