# Generated by Django 5.1.4 on 2024-12-23 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_course_professor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='room',
            name='capacity',
        ),
    ]
